services:
  keycloak:
    container_name: keycloak-test
    image: keycloak-test
    build: .
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HTTP_ENABLED=true
      - KC_HOSTNAME_STRICT=false
      - KC_HOSTNAME_STRICT_HTTPS=false
      - DEBUG=true
      - DEBUG_PORT=*:5005
    ports:
      - "8080:8080"
      - "5005:5005"
    command: "start"

  mockoon:
    container_name: mockoon
    image: mockoon/cli:9.2.0
    ports:
      - "3000:3000"
    command: [ "--data=/data/data.json" ]
    volumes:
      - "${PWD}/conf/mockoon:/data"