services:
  db:
    container_name: db-keycloak
    image: postgres:16.8
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=root
    - POSTGRES_DB=mydb
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 2s
      timeout: 1s
      retries: 2
    ports:
    - "5433:5432"
    volumes:
    - ./conf/db:/docker-entrypoint-initdb.d
    - db-keycloak-data:/var/lib/postgresql/data

  keycloak:
    container_name: custom-user-storage-keycloak
    build: .
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=admin
    - KC_HTTP_ENABLED=true
    - KC_HOSTNAME_STRICT=false
    - DEBUG=true
    - DEBUG_PORT=*:5005
    - DB_URL=host.docker.internal
    - DB_PORT=5433
    - DB_SCHEMA=mydb
    ports:
    - "8081:8080"
    - "5006:5005"
    command: [
      "start",
      "--verbose",
      "--log-level=INFO,org.keycloak.services.error.KeycloakErrorHandler:debug",
      "--import-realm",
      "--log-console-color=true"
    ]
    volumes:
    - ./conf/realms:/opt/keycloak/data/import

volumes:
  db-keycloak-data: