services:
  keycloak:
    container_name: keycloak
    image: keycloak-test
    build: .
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=root
      - DEBUG_PORT='*:8787'
      - REST_API_URL=http://host.docker.internal:3000/api
      #- KC_HTTPS_CERTIFICATE_FILE=/opt/keycloak/conf/server.crt.pem
      #- KC_HTTPS_CERTIFICATE_KEY_FILE=/opt/keycloak/conf/server.key.pem
    #volumes:
    #  - $PWD/keycloak/server.crt.pem:/opt/keycloak/conf/server.crt.pem
    #  - $PWD/keycloak/server.key.pem:/opt/keycloak/conf/server.key.pem
    ports:
      - "8787:8787"
      - "8080:8080"
      #- "8443:8443"
    command: "--debug --verbose start-dev"